export type Deal = {
  id: string;
  title: string;
  category: string;
  region: string;
  location: string;
  original_price: number;
  deal_price: number;
  total_qty: number;
  remaining_qty: number;
  closes_at: string; // ISO
  images?: string[];
  video_url?: string | null;
  seller_member_id?: string | null;
  seller_display_name?: string | null;
  description?: string;
  status?: "active" | "closed";
  package_unit?: string | null; // 포장 단위 (예: "20kg 박스")
  origin?: string | null; // 원산지
  spec?: string | null; // 규격/사이즈
  storage_condition?: string | null; // 보관조건 · 유통기한
  quantity_unit?: string | null; // 수량 단위 (박스/개/kg/톤/팔레트 등) — 없으면 "개"로 표시
  min_order_qty?: number | null; // 최소주문수량(MOQ)
  created_at?: string; // ISO — mock 데이터엔 없음
};

export const quantityUnits = ["개", "박스", "kg", "톤", "팔레트", "세트"];

const now = Date.now();

// UI 데모용 더미 이미지/영상(loremflickr.com 키워드 기반 사진, 자동차 소개영상 샘플 1건) —
// 실제 매물 사진/영상 아님. Supabase 미설정(로컬 dev/일부 프리뷰) 상태에서만 쓰이는 fallback 데이터라
// 운영 DB(deals 테이블)에는 영향 없음. mockCategories 18개 전부 1건씩 매핑.
export const mockDeals: Deal[] = [
  {
    id: "1",
    title: "냉동 삼겹살 대패 10kg x 30박스",
    category: "냉동냉장식품",
    region: "서울",
    location: "서울 가락동",
    original_price: 620000,
    deal_price: 398000,
    total_qty: 30,
    remaining_qty: 21,
    closes_at: new Date(now + 1000 * 60 * 60 * 4.2).toISOString(),
    images: ["/images/mock/pork-belly-1.jpg", "/images/mock/pork-belly-2.jpg"],
    video_url: null,
    description: "냉동 보관 · 박스당 10kg 균일 포장 · 소비기한 여유 3개월 이상",
    package_unit: "10kg 박스",
    origin: "국내산",
    storage_condition: "냉동보관",
    quantity_unit: "박스",
    min_order_qty: 5,
  },
  {
    id: "2",
    title: "국내산 갈치 20kg 박스",
    category: "농수축산물",
    region: "서울",
    location: "서울 가락동",
    original_price: 380000,
    deal_price: 219000,
    total_qty: 55,
    remaining_qty: 12,
    closes_at: new Date(now + 1000 * 60 * 60 * 2.97).toISOString(),
    images: ["/images/mock/hairtail-1.jpg", "/images/mock/hairtail-2.jpg"],
    video_url: null,
    description: "소비기한 등록일로부터 5일 · 냉동 보관 · 박스당 20kg 균일 포장 · 원산지 증명서 제공 가능",
    package_unit: "20kg 박스",
    origin: "국내산 (제주)",
    storage_condition: "냉동보관 · 소비기한 등록일로부터 5일",
    quantity_unit: "박스",
    min_order_qty: 5,
  },
  {
    id: "3",
    title: "스테인리스 텀블러 500ea",
    category: "생활용품",
    region: "인천",
    location: "인천 남동공단",
    original_price: 4200,
    deal_price: 2300,
    total_qty: 500,
    remaining_qty: 340,
    closes_at: new Date(now + 1000 * 60 * 60 * 11.66).toISOString(),
    images: ["/images/mock/tumbler-1.jpg"],
    video_url: null, // TODO: tumbler.mp4 파일 확보되면 "/videos/mock/tumbler.mp4"로 교체
    description: "박스 및 개별 포장 상태 양호 · 사용 흔적 없는 신품 재고 · KC 인증서 보유",
    package_unit: "1개입 개별포장 · 50개입 박스",
    origin: "중국",
    spec: "500ml, 지름 7cm x 높이 22cm",
    quantity_unit: "개",
    min_order_qty: 50,
  },
  {
    id: "4",
    title: "계절 재고 우산 1,200개",
    category: "패션잡화",
    region: "경기",
    location: "경기 부천",
    original_price: 3500,
    deal_price: 1900,
    total_qty: 1200,
    remaining_qty: 1080,
    closes_at: new Date(now + 1000 * 60 * 60 * 28.2).toISOString(),
    images: ["/images/mock/umbrella-1.jpg", "/images/mock/umbrella-2.jpg"],
    video_url: "/videos/mock/umbrella.mp4",
    description: "전 시즌 이월 재고 · 박스 단위(50개입) 판매 · 색상 랜덤 혼합 구성",
  },
  {
    id: "5",
    title: "명품 라인 립스틱 재고 800개",
    category: "화장품",
    region: "경기",
    location: "경기 이천",
    original_price: 28000,
    deal_price: 12900,
    total_qty: 800,
    remaining_qty: 512,
    closes_at: new Date(now + 1000 * 60 * 60 * 9.3).toISOString(),
    images: ["https://loremflickr.com/800/600/lipstick,cosmetics", "https://loremflickr.com/800/600/makeup,cosmetics"],
    video_url: null,
    description: "정품 인증서 보유 · 색상 혼합 구성 · 유통기한 1년 이상",
  },
  {
    id: "6",
    title: "리퍼비시 무선 이어폰 3,000개",
    category: "전자제품",
    region: "서울",
    location: "서울 구로디지털",
    original_price: 32000,
    deal_price: 15900,
    total_qty: 3000,
    remaining_qty: 2140,
    closes_at: new Date(now + 1000 * 60 * 60 * 6.5).toISOString(),
    images: ["https://loremflickr.com/800/600/earbuds,electronics"],
    video_url: null,
    description: "박스 개봉·기능 검수 완료 · 정품 충전케이스 포함 · A/S 불가 명시 필요",
  },
  {
    id: "7",
    title: "산업용 스테인리스 원자재 10톤",
    category: "산업원자재",
    region: "경남",
    location: "경남 김해",
    original_price: 42000000,
    deal_price: 29800000,
    total_qty: 10,
    remaining_qty: 4,
    closes_at: new Date(now + 1000 * 60 * 60 * 5.4).toISOString(),
    images: ["https://loremflickr.com/800/600/steel,industrial", "https://loremflickr.com/800/600/metal,factory"],
    video_url: null,
    description: "재질 증명서(밀시트) 제공 · 규격 균일 · 직접 방문 실사 가능 · 지게차 상차 지원",
  },
  {
    id: "8",
    title: "중고 진공포장기 15대",
    category: "기계설비",
    region: "충북",
    location: "충북 음성",
    original_price: 1800000,
    deal_price: 980000,
    total_qty: 15,
    remaining_qty: 9,
    closes_at: new Date(now + 1000 * 60 * 60 * 20).toISOString(),
    images: ["https://loremflickr.com/800/600/machine,industrial"],
    video_url: null,
    description: "가동 확인 완료 · 공장 직권 처분 · 상차 지원 가능",
  },
  {
    id: "9",
    title: "유통기한 임박 즉석카레 5,000개",
    category: "가공식품·잡화",
    region: "충남",
    location: "충남 아산",
    original_price: 2800,
    deal_price: 1100,
    total_qty: 5000,
    remaining_qty: 3200,
    closes_at: new Date(now + 1000 * 60 * 60 * 8.1).toISOString(),
    images: ["https://loremflickr.com/800/600/curry,food"],
    video_url: null,
    description: "유통기한 3주 이내 · 박스당 40개입 · 상온 보관",
    storage_condition: "상온보관 · 유통기한 임박",
  },
  {
    id: "10",
    title: "리퍼 사무용 책상 200개",
    category: "가구",
    region: "경기",
    location: "경기 파주",
    original_price: 95000,
    deal_price: 42000,
    total_qty: 200,
    remaining_qty: 130,
    closes_at: new Date(now + 1000 * 60 * 60 * 33).toISOString(),
    images: ["https://loremflickr.com/800/600/desk,office"],
    video_url: null,
    description: "전시/반품 재고 · 경미한 스크래치 있음 · 직접 수령 가능",
  },
  {
    id: "11",
    title: "1회용 마스크 KF94 50,000매",
    category: "건강·위생용품",
    region: "대구",
    location: "대구 성서공단",
    original_price: 350,
    deal_price: 150,
    total_qty: 50000,
    remaining_qty: 41000,
    closes_at: new Date(now + 1000 * 60 * 60 * 15.7).toISOString(),
    images: ["https://loremflickr.com/800/600/mask,medical"],
    video_url: null,
    description: "KC 인증 완료 · 50매입 박스 단위 · 개별포장",
    quantity_unit: "매",
  },
  {
    id: "12",
    title: "반품 노트북 재고 120대",
    category: "IT·사무기기",
    region: "서울",
    location: "서울 성수동",
    original_price: 890000,
    deal_price: 520000,
    total_qty: 120,
    remaining_qty: 77,
    closes_at: new Date(now + 1000 * 60 * 60 * 12.4).toISOString(),
    images: ["https://loremflickr.com/800/600/laptop,computer", "https://loremflickr.com/800/600/laptop,office"],
    video_url: null,
    description: "단순변심 반품 · 미개봉/개봉 혼합 · 개별 검수표 제공",
  },
  {
    id: "13",
    title: "A4 복사용지 2,000박스",
    category: "사무용품·비품",
    region: "인천",
    location: "인천 부평",
    original_price: 24000,
    deal_price: 14500,
    total_qty: 2000,
    remaining_qty: 1650,
    closes_at: new Date(now + 1000 * 60 * 60 * 40).toISOString(),
    images: ["https://loremflickr.com/800/600/paper,office"],
    video_url: null,
    description: "박스당 5개입 · 창고 재고 정리",
  },
  {
    id: "14",
    title: "겨울용 스노우체인 800세트",
    category: "자동차용품",
    region: "강원",
    location: "강원 원주",
    original_price: 42000,
    deal_price: 19800,
    total_qty: 800,
    remaining_qty: 610,
    closes_at: new Date(now + 1000 * 60 * 60 * 50).toISOString(),
    images: ["https://loremflickr.com/800/600/tire,car"],
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    description: "시즌 오프 재고 · 규격별 혼합 구성",
  },
  {
    id: "15",
    title: "강아지 사료 15kg 300포",
    category: "반려동물용품",
    region: "전북",
    location: "전북 익산",
    original_price: 62000,
    deal_price: 38000,
    total_qty: 300,
    remaining_qty: 190,
    closes_at: new Date(now + 1000 * 60 * 60 * 18.9).toISOString(),
    images: ["https://loremflickr.com/800/600/dog,petfood"],
    video_url: null,
    description: "유통기한 6개월 이상 · 미개봉 · 파렛트 단위 상차",
    storage_condition: "상온보관",
  },
  {
    id: "16",
    title: "캐릭터 완구 재고 500개",
    category: "완구·유아용품",
    region: "충남",
    location: "충남 천안",
    original_price: 9900,
    deal_price: 4500,
    total_qty: 500,
    remaining_qty: 380,
    closes_at: new Date(now + 1000 * 60 * 60 * 24).toISOString(),
    images: ["https://loremflickr.com/800/600/toy,kids"],
    video_url: null,
    description: "KC 안전인증 완료 · 박스 단위 구성",
  },
  {
    id: "17",
    title: "창고 정리 혼합재고 팔레트 20개",
    category: "혼합재고",
    region: "경기",
    location: "경기 안성",
    original_price: 3000000,
    deal_price: 1200000,
    total_qty: 20,
    remaining_qty: 14,
    closes_at: new Date(now + 1000 * 60 * 60 * 60).toISOString(),
    images: ["https://loremflickr.com/800/600/warehouse,pallet"],
    video_url: null,
    description: "품목 혼합(생활용품·잡화 등) · 팔레트 단위 일괄 판매 · 직접 실사 권장",
  },
  {
    id: "18",
    title: "미분류 재고 잡화 1,000개",
    category: "기타",
    region: "부산",
    location: "부산 사상구",
    original_price: 5000,
    deal_price: 2200,
    total_qty: 1000,
    remaining_qty: 720,
    closes_at: new Date(now + 1000 * 60 * 60 * 16.2).toISOString(),
    images: ["https://loremflickr.com/800/600/warehouse,goods"],
    video_url: null,
    description: "분류 미정 잡화 혼합 · 박스 단위 랜덤 구성",
  },
];

export const mockCategories = [
  "냉동냉장식품",
  "농수축산물",
  "생활용품",
  "패션잡화",
  "화장품",
  "전자제품",
  "산업원자재",
  "기계설비",
  "가공식품·잡화",
  "가구",
  "건강·위생용품",
  "IT·사무기기",
  "사무용품·비품",
  "자동차용품",
  "반려동물용품",
  "완구·유아용품",
  "혼합재고",
  "기타",
];

export const categoryIcons: Record<string, string> = {
  냉동냉장식품: "🧊",
  농수축산물: "🌾",
  생활용품: "📦",
  패션잡화: "👜",
  화장품: "💄",
  전자제품: "🔌",
  산업원자재: "🏗️",
  기계설비: "⚙️",
  "가공식품·잡화": "🥫",
  가구: "🛋️",
  "건강·위생용품": "🧴",
  "IT·사무기기": "💻",
  "사무용품·비품": "🗄️",
  자동차용품: "🚗",
  반려동물용품: "🐾",
  "완구·유아용품": "🧸",
  혼합재고: "🔀",
  기타: "🗂️",
};

// 카테고리마다 고유 컬러를 줘서 리스트에서 한눈에 구분되게 합니다.
export const categoryColors: Record<string, { bg: string; text: string; solid: string }> = {
  냉동냉장식품: { bg: "#E0F7FA", text: "#0E7C82", solid: "#17B8C4" },
  농수축산물: { bg: "#E8F8EC", text: "#1D8A44", solid: "#34C471" },
  생활용품: { bg: "#F3EBFF", text: "#7A3FC2", solid: "#9B5DE5" },
  패션잡화: { bg: "#FFE9F3", text: "#C22B72", solid: "#F5439B" },
  화장품: { bg: "#FFEAF0", text: "#C22050", solid: "#FF5C8A" },
  전자제품: { bg: "#EDEBFF", text: "#4C3FB8", solid: "#6C5CE7" },
  산업원자재: { bg: "#F5EDE4", text: "#7A5230", solid: "#A9744F" },
  기계설비: { bg: "#EAEDF5", text: "#3D4A66", solid: "#5C6B8C" },
  "가공식품·잡화": { bg: "#FFF4E0", text: "#966B00", solid: "#F5A623" },
  가구: { bg: "#FDE9E0", text: "#B84A24", solid: "#E8794A" },
  "건강·위생용품": { bg: "#E6F9F1", text: "#0F7A5C", solid: "#2BB894" },
  "IT·사무기기": { bg: "#E7F0FF", text: "#1D4FA0", solid: "#3E7BFA" },
  "사무용품·비품": { bg: "#EEF1F5", text: "#45505E", solid: "#7C8BA0" },
  자동차용품: { bg: "#FDEBEA", text: "#A32B2B", solid: "#E5484D" },
  반려동물용품: { bg: "#FFF6DE", text: "#8A6100", solid: "#F2B705" },
  "완구·유아용품": { bg: "#E9F6FF", text: "#0B6FA6", solid: "#38B6FF" },
  혼합재고: { bg: "#F2F1E6", text: "#6B6420", solid: "#B5A642" },
  기타: { bg: "#F1F1EF", text: "#5C5C57", solid: "#8A8A82" },
};

export const mockRegions = [
  "서울",
  "부산",
  "대구",
  "인천",
  "광주",
  "대전",
  "울산",
  "세종",
  "경기",
  "강원",
  "충북",
  "충남",
  "전북",
  "전남",
  "경북",
  "경남",
  "제주",
];
